### ISSUE TITLE
How about an example docs page, for buildDocs itself? 

### ISSUE THREAD

**Issue by gaborcsardi** [hafen/buildDocs#3]
So that we can see how it would look like. You can set it up to work from Travis CI.

**Comment by hafen** [comment]
Good idea.  Actually, I'm supplanting this package with a new one, "packagedocs" in the next few days - this one was a bit hacky and persnickety and didn't work with rmarkdown, which makes it difficult to include things like htmlwidgets, etc.  I need to make some css fixes but will push it up soon.  An example of it in use is here: http://hafen.github.io/rbokeh/

**Comment by gaborcsardi** [comment]
packagedocs is awesome, btw.

**Comment by hafen** [comment]
Thanks @gaborcsardi!  While I wrote it to fill some of my own needs, I'd like to make sure it is flexible enough for others to use.  Feel free to fire away with issues if there are things you'd like to see.
